name = "Horror Mods"
author = "LPbigFish"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79052c48004bf68a44aae0d8f10f6ccf423677b909abd9508b11e2e86e071a28"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
