name = "Horror Mods"
author = "LPbigFish"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c3b2688a19967dcc527bc0ce2fb90feda29a8801768b1e0bda150a496ce9bcb"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
